# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nixcopy < Formula
  desc "Fast universal file-transfer CLI — SFTP, FTPS, Azure Blob, AWS S3, local disk"
  homepage "https://github.com/preedep/go-nixcopy"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/preedep/go-nixcopy/releases/download/v1.3.1/nixcopy_1.3.1_darwin_amd64.tar.gz"
      sha256 "273064ec73675da52a8dbab442455081f34eaf3fe998970bf4b3010471e735d2"

      define_method(:install) do
        bin.install "nixcopy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/preedep/go-nixcopy/releases/download/v1.3.1/nixcopy_1.3.1_darwin_arm64.tar.gz"
      sha256 "f36f6f7fbea3aa34db2f5e024d082034010b28f36811c1dc4011fa81102b386d"

      define_method(:install) do
        bin.install "nixcopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/preedep/go-nixcopy/releases/download/v1.3.1/nixcopy_1.3.1_linux_amd64.tar.gz"
      sha256 "d33b1f7603fd5246602ff48259bd4f1c5ad7822ce0d7917f6c25207400c77fb4"
      define_method(:install) do
        bin.install "nixcopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/preedep/go-nixcopy/releases/download/v1.3.1/nixcopy_1.3.1_linux_arm64.tar.gz"
      sha256 "3ead1fcfec1c3b3fa68d50438762a6fad5ecbee83b37da17c6569305e4d28c94"
      define_method(:install) do
        bin.install "nixcopy"
      end
    end
  end

  test do
    system "#{bin}/nixcopy --version"
  end
end
