# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nixcopy < Formula
  desc "Fast universal file-transfer CLI — SFTP, FTPS, Azure Blob, AWS S3, local disk"
  homepage "https://github.com/preedep/go-nixcopy"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/preedep/go-nixcopy/releases/download/v1.2.0/nixcopy_1.2.0_darwin_amd64.tar.gz"
      sha256 "18410b4279382ce3ebef75dd70a4367411f75d724edbd6645c134319a37159c5"

      define_method(:install) do
        bin.install "nixcopy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/preedep/go-nixcopy/releases/download/v1.2.0/nixcopy_1.2.0_darwin_arm64.tar.gz"
      sha256 "406d74650f9edf64403d6c39e20d460fbb377ecc19ed2c0c86307d4e530861ef"

      define_method(:install) do
        bin.install "nixcopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/preedep/go-nixcopy/releases/download/v1.2.0/nixcopy_1.2.0_linux_amd64.tar.gz"
      sha256 "837f93aa8fc96929c7063e2a5ebb58fd85dbdce15867c36f2b1c18ec663fbf3a"
      define_method(:install) do
        bin.install "nixcopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/preedep/go-nixcopy/releases/download/v1.2.0/nixcopy_1.2.0_linux_arm64.tar.gz"
      sha256 "e9597ec41c752bd032b91c9c86f93ec3ea35320a7c8ff8a86bcad8fe74ff5e09"
      define_method(:install) do
        bin.install "nixcopy"
      end
    end
  end

  test do
    system "#{bin}/nixcopy --version"
  end
end
