# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nixcopy < Formula
  desc "Fast universal file-transfer CLI — SFTP, FTPS, Azure Blob, AWS S3, local disk"
  homepage "https://github.com/preedep/go-nixcopy"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/preedep/go-nixcopy/releases/download/v1.2.0/nixcopy_1.2.0_darwin_amd64.tar.gz"
      sha256 "ad5fa36ef8af3133615bf9077223a836e3e9eca8cc27545b0d76fadb3a65dfdc"

      define_method(:install) do
        bin.install "nixcopy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/preedep/go-nixcopy/releases/download/v1.2.0/nixcopy_1.2.0_darwin_arm64.tar.gz"
      sha256 "2adfc2747a9a93de67c4314927b2b6258fa6c002052f5047cce9f32e9e1f9c4a"

      define_method(:install) do
        bin.install "nixcopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/preedep/go-nixcopy/releases/download/v1.2.0/nixcopy_1.2.0_linux_amd64.tar.gz"
      sha256 "cd01bad77d9c61b7ec9b39c3b6e4f88d1667c72d8d9efe7b036affb529033239"
      define_method(:install) do
        bin.install "nixcopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/preedep/go-nixcopy/releases/download/v1.2.0/nixcopy_1.2.0_linux_arm64.tar.gz"
      sha256 "9dcb5f49aff816eb4a69bb4859e46eb4c18a8cd08077d85ea6e26a4e544e8364"
      define_method(:install) do
        bin.install "nixcopy"
      end
    end
  end

  test do
    system "#{bin}/nixcopy --version"
  end
end
